name = "create-private"
author = "d513"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10e72367bccb89c52d288f7f90366d0f882f39d6f390286e4d4df908d9b2a758"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
