name = "create-private"
author = "d513"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8fd1924246908276d910bffd1a6576a8164bfecd102851172b64285e062cf74"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
