name = "create-private"
author = "d513"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89947cd0a37b6e1b0660f6ea57e5f0b2125b7140c5cd1364f9062177fe863875"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
