name = "create-private"
author = "d513"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89bab831964aaa566d075464892bda39b9927df1c940c7d5504cbd6da32b1a4d"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
