name = "create-private"
author = "d513"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4dbe25d72860a64d3eaa112f1043c632419fd679908297d9c3341b5fe09f7c1c"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
