name = "create-private"
author = "d513"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "baf48f8097692d2917ada15db206469e55b8185b1fa17bbc7aa510af1a8782be"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
