name = "create-private"
author = "d513"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c77245314c84b9fb7bd34da51acdb5e4ba7d0988cb9f1c42a175c531a4258dee"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
