name = "create-private"
author = "d513"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6751dec17ccbf9082a69fbf2ab6075195f9017c0f388dc2301cc8fed24470232"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
