name = "create-private"
author = "d513"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e9adc698bbc8d598899bbacafd8ff14bb8e4c06d470c4c48adafadc966c26b5"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
