name = "create-private"
author = "d513"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d2507a44838e5c567a7c8b51b5892c0935b2705038e354c653efe6ca0d923ca"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
