name = "create-private"
author = "d513"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79f7e36d9ca4926f89ee310a42cffd2758435d9be883390a3a2547781477fe40"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
