name = "create-private"
author = "d513"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ad77d7e682e79d503ed945c0d5e7668f534e6b28655f4fc96cb27721711f81e"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
